accounts/urls.py
from django.urls import path
from .views import login_page, register_page, guest_register_view
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path('login/', login_page, name="login"),
    path('register/', register_page, name="register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('guest/register/', guest_register_view, name="guest_register"),

]

addresses/urls.py
from django.urls import path
from .views import checkout_address_create_view, checkout_address_reuse_view,sendmail
app_name = "addresses"

urlpatterns = [
    path('checkout-create-view', checkout_address_create_view, name="checkout_create_view"),
    path('checkout-reuse-view', checkout_address_reuse_view, name="checkout_reuse_view"),
]

carts/urls.py
from django.urls import path
from .views import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view,cart_image_upload

app_name = "carts"

urlpatterns = [
    path('', cart_home, name="home"),
    path('api/', cart_detail_api_view, name="home_api"),
    path('checkout/', checkout_home, name="checkout"),
    path('update/', cart_update, name="update"),
    path('success/', checkout_done_view, name="success"),
    path('update_receipt/', cart_image_upload,name="update_receipt"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, contact_page, profile_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="home_url"),
    path('contact/', contact_page, name="contact_url"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('addresses/', include('addresses.urls')),
    path('cart/', include('carts.urls')),
    path('search/', include('search.urls')),
    path('profile', profile_page, name="profile_url"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.conf import settings
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed
from decimal import Decimal

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user             
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    total = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    receipt = models.ImageField(upload_to="cart", height_field=None, width_field=None, max_length=100, default="")
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

class ProductCount(models.Model):
    cart_id = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True, blank=True)
    product_id = models.ForeignKey(Product, verbose_name="Product", on_delete=models.SET_NULL, null=True, blank=True)
    count = models.IntegerField(default=1)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()        
        total = 0
        for x in products:
            try:
                if instance.productcount_set.filter(product_id=x.id).get():
                    product_count = instance.productcount_set.filter(product_id=x.id).get()
                    total += x.price * product_count
            except instance.productcount_set.DoesNotExist:
                total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0


pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/forms.py
from django import forms
from .models import Cart


class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Cart
        fields = [
                'receipt'
                ]

carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from products.models import Product
from .models import Cart, ProductCount
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address
import json
from decimal import Decimal
from django.db.models import Q
from django.http import HttpResponse
from carts.forms import ImageForm
from django.core.mail import send_mail
import os
from django.conf import settings

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
        'id': x.product_id.id,
        'url': x.product_id.get_absolute_url(),
        'title': x.product_id.title,
        'price': format(x.product_id.price, '.2f')
    } for x in cart_obj.productcount_set.all()]
    cart_data = {
        'products': products,
        'subTotal': format(cart_obj.subtotal, '.2f'),
        'total': format(cart_obj.total, '.2f')
    }
    return JsonResponse(cart_data, status=200)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    cart_id = request.POST.get('cart_id')
    qty = request.POST.get('qty')
    if product_id is not None:

        # get product or return cart page
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            # ajax error response
            if request.is_ajax():
                json_data = {
                    'added': False,
                    'removed': False,
                }
                return JsonResponse(json_data, status=409)

            return redirect("carts:home")

        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if qty is not None:
            obj = ProductCount.objects.get(cart_id=cart_id, product_id=Product.objects.get(id=product_id))
            if obj:
                obj.count = qty
                obj.save()
            product_added = True
        elif product_obj in cart_obj.products.all():
            # remove product cart
            cart_obj.products.remove(product_obj)
            cart_obj.productcount_set.filter(product_id=product_obj.id).delete()
                
            product_added = False
        else:
            # add product cart3
            cart_obj.products.add(product_obj)
            ProductCount.objects.create(cart_id=cart_obj, product_id=Product.objects.get(id=product_id), count=1)
            product_added = True

        # cart product count update
        request.session['cart_items'] = cart_obj.products.count()
        if request.is_ajax():
            json_data = {
                'added': product_added,
                'removed': not product_added,
                'cartItemCount': cart_obj.products.count(),
            }
            return JsonResponse(json_data, status=200)

    # no product_id in post request
    return redirect("carts:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    billing_address_id = request.session.get('billing_address_id', None)
    shipping_address_id = request.session.get('shipping_address_id', None)

    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)

        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session['billing_address_id']
        if billing_address_id or shipping_address_id:
            order_obj.save()
           
    if request.method == 'POST':
        "some check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            request.session['order_code'] = request.POST.get('order_code')
            subject = 'order'
            message = f'Hi {request.user.username}, thank you for order.'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [request.user.email, ]
            send_mail( subject, message, email_from, recipient_list )   

            return redirect("carts:success")

    context = {
        'object': order_obj,
        'billing_profile': billing_profile,
        'login_form': LoginForm(),
        'guest_form': GuestForm(),
        'address_form': AddressForm(),
        'address_qs': address_qs,
    }

    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    context = {
        "order_code": request.session['order_code']
    }
    return render(request, "carts/checkout-done.html", context)

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
def cart_image_upload(request):    
    if request.method == 'POST': 
        cart_id = request.POST.get('cart_id',"") 
        old = Cart.objects.get(id=cart_id)
        form = ImageForm(request.POST, request.FILES, instance=old)
        if form.is_valid():         
            form.save()
            return JsonResponse({'error': False, 'message': 'Uploaded Successfully'})
        else:
           return JsonResponse({'error': True, 'errors': form.errors})

templates/carts/checkout-done.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}
    Checkout Done
{% endblock %}

{% block content %}
    <div class="col-6 mx-auto py-5 text-center">
        <h1 class="display-1"> Thank you for your order.</h1>
        <p><b>Order Code: </b> {{ order_code }}</p>
        <a class="btn btn-info" href="{% url 'home_url' %}"> Return Home</a>
    </div>
{% endblock %}

templates/carts/checkout.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}
    Checkout
{% endblock %}

{% block content %}
{{ object.order_code }} -- {{ object.cart.id }}

    {% if not billing_profile %}
        <div class="row">
            <div class="col-12 col-md-6">
                <p class="lead text-center"><b>Login</b></p>
                     <div class="row d-flex justify-content-center">
                        <div class="col-6">
                            {% include "accounts/snippets/login_form.html" with form=login_form next_url=request.build_absolute_uri %}
                        </div>
                    </div>
            </div>
            <div class="col-12 col-md-6 text-center">
                <b>Continue as Guest</b>
                 <div class="row d-flex justify-content-center">
                    <div class="col-6">
                        {% url 'accounts:guest_register' as guest_register_url %}
                        {% include "accounts/snippets/login_form.html" with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
                    </div>
                 </div>
            </div>
        </div>
    {% else %}

        {% if not object.shipping_address %}
             <div class="row d-flex justify-content-center">
                <div class="col-12 pt-5">
                    <p class="lead">Shipping Address</p>
                    <hr>
                </div>
                <div class="col-6">
                    {% url 'addresses:checkout_create_view' as checkout_create_view %}
                    {% include "addresses/snippets/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_create_view address_type='shipping' %}
                </div>
                 <div class="col-6">
                      {% url 'addresses:checkout_reuse_view' as checkout_reuse_view %}
                      {% include 'addresses/snippets/prev_addresses.html' with addresses_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_reuse_view %}
                 </div>
             </div>
        {% elif not object.billing_address %}
             <div class="row d-flex justify-content-center">
                <div class="col-12 pt-5">
                    <p class="lead">Billing Address</p>
                    <hr>
                </div>
                <div class="col-6">
                    {% url 'addresses:checkout_create_view' as checkout_create_view %}
                    {% include "addresses/snippets/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_create_view address_type='billing' %}
                </div>
              <div class="col-6">
                      {% url 'addresses:checkout_reuse_view' as checkout_reuse_view %}
                      {% include 'addresses/snippets/prev_addresses.html' with addresses_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_reuse_view %}
                 </div>
             </div>
        {% else %}
            <h1>Checkout</h1>
            <p>Cart Items:
                {% for prodcut in object.cart.products.all %}
                    {{ prodcut }} {% if not forloop.last %},{% endif %}
                {% endfor %}
            </p>
            <p>Cart Total: {{ object.cart.total|floatformat:2|localize }}</p>
            <p>Shipping Address: {{ object.shipping_address.get_address|safe }}</p>
            <p>Billing Address: {{ object.billing_address.get_address|safe }}</p>
            <p>Shipping Total: {{ object.shipping_total|floatformat:2|localize }}</p>
            <p>Total: {{ object.order_total|floatformat:2|localize }}</p>
            <form class="form" method="post" action="{% url 'carts:checkout' %}">{% csrf_token %}
                <input type="hidden" name="order_code" value="{{ object.order_code }}">
                <button type="submit" class="btn btn-success">Checkout</button>
            </form>
        {% endif %}
    {% endif %}

{% endblock %}

templates/carts/home.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<div class="alert alert-danger" role="alert">
  <strong>PAY NOW & UPLOAD</strong> Use any one of the payment method in below table for sending money 
  and upload your receipt before clicking checkout button then only we can process your order.
</div>
    <table class="table table-striped">
      <thead>
        <th><span class="badge badge-info"><i class="fas fa-rupee-sign"></i></span> For Bank Transfer Account Details</th>
        <!-- <th><span class="badge badge-info"><i class="fab fa-google-pay"></i></span> For GooglePay </th>
        <th><span class="badge badge-info"><i class="far fa-credit-card"></i></span> For PhonePe </th>
        <th><span class="badge badge-info"><i class="far fa-credit-card"></i></span> For Paytm </th> -->
        </thead>
        <tbody>
          <tr>
            <td>
              NAME: <b>T.Immon santhosh</b> <br>
              ACCOUNT NUMBER: <b>500101011889772</b><br>
              IFSC CODE: <b>CIUB0000048</b><br>
              BRANCH: <b>tirunelveli-town</b>
            </td>
            <!-- <td>
              PHONE NUMBER: <b> +91 9361765096</b>
            </td>
            <td>
              PHONE NUMBER: <b> +91 9361765096</b>
            </td>
            <td>
              PHONE NUMBER: <b> +91 9361765096</b>
            </td> -->
          </tr>
      </tbody>
  </table>
    <h1>Cart</h1>
    {% if cart.products.exists %}
        <table class="table cart-table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product Name</th>
              <th scope="col">Product Price</th>
                <th scope="col">Qty</th>
              <th scope="col">Edit</th>
            </tr>
          </thead>
          <tbody class="cart-body">
            {% for pc in cart.productcount_set.all %}
                <tr class="cart-products">
                  <th scope="row">{{ forloop.counter }}</th>
                  <td><a href="/products/detail/{{pc.product_id.slug }}">{{pc.product_id.title}}</a></td>
                  <td>{{pc.product_id.price|floatformat:2|localize }}</td>
                    <td>
                     <div class="form-group col-md-12">
                      <label class="control-label col-sm-2 col-md-6" for="qty{{pc.product_id.id}}">Product Count:</label>
                      <div class="col-sm-2 col-md-6">
                          <form class="form form-product-ajax" method="POST" action="{% url 'carts:update' %}" data-endpoint="{% url 'carts:home_api' %}">
                            {% csrf_token %}
                               <input class="cart-item-product-id" type="hidden" name="product_id" value="{{ pc.product_id.id }}">
                              <input class="cart-id" type="hidden" name="cart_id" value="{{ pc.cart_id }}">
                        <input type="number" class="form-control" id="qty{{pc.product_id.id}}" value="{{pc.count}}" name="qty" min="1" oninput="this.value =
 !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null" onchange="this.form.submit()">

                          </form>
                      </div>
                    </div>
                    </td>
                  <td>
                     {% include "carts/snippets/remove-product.html" with product_id=pc.product_id.id cart=cart %}
                  </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="3"></td>
                <td><b>Subtotal: </b> <span class="cart-subTotal">{{ cart.subtotal|floatformat:2|localize }}</span> ₹</td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <td><b>Total: </b> <span class="cart-total">{{ cart.total|floatformat:2|localize }}</span> ₹</td>
            </tr>
            <tr>
                <td colspan="3"></td>                
                <td>
                  <form method="post" enctype="multipart/form-data" id="formimage">
                    {% csrf_token %}
                    <b>Upload your Receipt: </b>
                    <input type="hidden" value="{{ cart }}" name="cart_id"  id="cart_id"/>
                    <input type="file" id="receipt" name="receipt" id="file" required/>
                    <input type="submit" value="save" />
                  </form>
                </td>
                <td><button id="checkout" class="btn btn-block btn-success" onclick="window.location.href='{% url "carts:checkout" %}';" {% if not cart.receipt %} disabled {%endif%} >Checkout</button>
                {% if cart.receipt  %}
                <a href="/media/{{ cart.receipt }}">click to view uploaded receipt file</a>
                {% endif %}
                </td>
            </tr>
          </tbody>
        </table>        
        <div class="cart-item-remove-form" style="display: none">
            {% include 'carts/snippets/remove-product.html' %}
        </div>
    {% else %}
        <p class="lead">Cart is empty.</p>
    {% endif %}
    <script>
      var token = '{{csrf_token}}';
      $(document).ready(
    function(){
       
                  $("#formimage").submit(function(e) {
                      e.preventDefault(); 
                      var formData = new FormData(this);
                    $.ajax({
                          headers: { "X-CSRFToken": token },
                          url : "{% url 'carts:update_receipt' %}",
                          type : 'POST',
                          data : formData,
                          processData: false,  // tell jQuery not to process the data
                          contentType: false,  // tell jQuery not to set contentType
                          success : function(data) {                              
                              alert("uploaded success");
                              $('#checkout').attr('disabled',false);
                          },
                          error: function (err) {
                            alert("error please contact website");
                            $('#checkout').attr('disabled',true);
                          }
                      });                
                    });                
               
    });
   
    </script>
{% endblock %}

{% block bottom %}
    {% include 'carts/snippets/cart-ajax.html' %}
{% endblock %}